fs.M1.P1_state[0.0].enth_mass_phase[Liq]: 99740.72571999984
fs.M1.P1_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.48768430557756287
fs.M1.P1_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.017688031808512642
fs.M1.P1_state[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9650000000000001
fs.M1.P1_state[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.M1.P1_state[0.0].pressure: 7492887.151347015
fs.M1.P1_state[0.0].temperature: 298.15
fs.M1.P2_state[0.0].enth_mass_phase[Liq]: 99740.72571999991
fs.M1.P2_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.M1.P2_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.M1.P2_state[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.M1.P2_state[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.M1.P2_state[0.0].pressure: 7492887.151347015
fs.M1.P2_state[0.0].temperature: 298.15
fs.M1.mixed_state[0.0].enth_mass_phase[Liq]: 99740.72571999986
fs.M1.mixed_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.9857088999999999
fs.M1.mixed_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035751099999999994
fs.M1.mixed_state[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.M1.mixed_state[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.M1.mixed_state[0.0].pressure: 7492887.151347015
fs.M1.mixed_state[0.0].temperature: 298.15
fs.P1.control_volume.deltaP[0.0]: 7391562.151347015
fs.P1.control_volume.properties_in[0.0].enth_mass_phase[Liq]: 99740.72571999999
fs.P1.control_volume.properties_in[0.0].flow_mass_phase_comp[Liq,H2O]: 0.48768430557756287
fs.P1.control_volume.properties_in[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.017688031808512642
fs.P1.control_volume.properties_in[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9650000000000001
fs.P1.control_volume.properties_in[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.P1.control_volume.properties_in[0.0].pressure: 101325.0
fs.P1.control_volume.properties_in[0.0].temperature: 298.15
fs.P1.control_volume.properties_out[0.0].dens_mass_phase[Liq]: 1021.46
fs.P1.control_volume.properties_out[0.0].enth_mass_phase[Liq]: 99740.72571999989
fs.P1.control_volume.properties_out[0.0].flow_mass_phase_comp[Liq,H2O]: 0.48768430557756287
fs.P1.control_volume.properties_out[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.017688031808512642
fs.P1.control_volume.properties_out[0.0].flow_vol_phase[Liq]: 0.0004947548972902272
fs.P1.control_volume.properties_out[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9650000000000001
fs.P1.control_volume.properties_out[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.P1.control_volume.properties_out[0.0].temperature: 298.15
fs.P1.control_volume.work[0.0]: 4571.264466255028
fs.P1.costing.capital_cost: 8721.972601614594
fs.P1.ratioP[0.0]: 73.94904664541835
fs.P1.work_fluid[0.0]: 3657.011573004023
fs.P2.control_volume.deltaP[0.0]: 506587.22341861285
fs.P2.control_volume.properties_in[0.0].enth_mass_phase[Liq]: 99740.72571999989
fs.P2.control_volume.properties_in[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.P2.control_volume.properties_in[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.P2.control_volume.properties_in[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.P2.control_volume.properties_in[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.P2.control_volume.properties_in[0.0].pressure: 6986299.927928403
fs.P2.control_volume.properties_in[0.0].temperature: 298.15
fs.P2.control_volume.properties_out[0.0].dens_mass_phase[Liq]: 1021.46
fs.P2.control_volume.properties_out[0.0].enth_mass_phase[Liq]: 99740.72571999994
fs.P2.control_volume.properties_out[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.P2.control_volume.properties_out[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.P2.control_volume.properties_out[0.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.P2.control_volume.properties_out[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.P2.control_volume.properties_out[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.P2.control_volume.properties_out[0.0].pressure: 7492887.151347015
fs.P2.control_volume.properties_out[0.0].temperature: 298.15
fs.P2.control_volume.work[0.0]: 319.93839215949436
fs.P2.costing.capital_cost: 610.4424522403153
fs.P2.ratioP[0.0]: 1.0725115194945298
fs.P2.work_fluid[0.0]: 255.95071372759554
fs.PXR.costing.capital_cost: 973.1020678190223
fs.PXR.high_pressure_side.deltaP[0.0]: -7247342.029398318
fs.PXR.high_pressure_side.properties_in[0.0].dens_mass_phase[Liq]: 1045.9125190112295
fs.PXR.high_pressure_side.properties_in[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.PXR.high_pressure_side.properties_in[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035587728093265734
fs.PXR.high_pressure_side.properties_in[0.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.PXR.high_pressure_side.properties_in[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9326553981332943
fs.PXR.high_pressure_side.properties_in[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.06734460186670563
fs.PXR.high_pressure_side.properties_in[0.0].pressure: 7348667.029398319
fs.PXR.high_pressure_side.properties_in[0.0].temperature: 298.1500072638073
fs.PXR.high_pressure_side.properties_out[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.PXR.high_pressure_side.properties_out[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035587728093265734
fs.PXR.high_pressure_side.properties_out[0.0].pressure: 101325.0
fs.PXR.high_pressure_side.properties_out[0.0].temperature: 298.1500072638073
fs.PXR.low_pressure_side.deltaP[0.0]: 6884974.927928402
fs.PXR.low_pressure_side.properties_in[0.0].dens_mass_phase[Liq]: 1021.46
fs.PXR.low_pressure_side.properties_in[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.PXR.low_pressure_side.properties_in[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.PXR.low_pressure_side.properties_in[0.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.PXR.low_pressure_side.properties_in[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.PXR.low_pressure_side.properties_in[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.03500000000000001
fs.PXR.low_pressure_side.properties_in[0.0].pressure: 101325.0
fs.PXR.low_pressure_side.properties_in[0.0].temperature: 298.15
fs.PXR.low_pressure_side.properties_out[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.PXR.low_pressure_side.properties_out[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.PXR.low_pressure_side.properties_out[0.0].pressure: 6986299.927928403
fs.PXR.low_pressure_side.properties_out[0.0].temperature: 298.15
fs.RO.feed_side.K[0.0,0.0,NaCl]: 3.4512803512388215e-05
fs.RO.feed_side.K[0.0,1.0,NaCl]: 2.7060824531310153e-05
fs.RO.feed_side.N_Re[0.0,0.0]: 339.4894225951861
fs.RO.feed_side.N_Re[0.0,1.0]: 164.77295340586087
fs.RO.feed_side.N_Sc_comp[0.0,0.0,NaCl]: 701.8820660532529
fs.RO.feed_side.N_Sc_comp[0.0,1.0,NaCl]: 727.7593431217747
fs.RO.feed_side.N_Sh_comp[0.0,0.0,NaCl]: 39.674400521449414
fs.RO.feed_side.N_Sh_comp[0.0,1.0,NaCl]: 30.98506199148124
fs.RO.area: 80.13575502542317
fs.RO.costing.capital_cost: 2404.0726507626946
fs.RO.costing.fixed_operating_cost: 480.81453015253896
fs.RO.feed_side.dP_dx[0.0,0.0]: -12678.679050434575
fs.RO.feed_side.dP_dx[0.0,1.0]: -5318.296444828698
fs.RO.feed_side.dh: 0.001691998543711759
fs.RO.feed_side.deltaP[0.0]: -144220.12194869615
fs.RO.feed_side.mass_transfer_term[0.0,Liq,H2O]: -0.49285444999999994
fs.RO.feed_side.mass_transfer_term[0.0,Liq,NaCl]: -0.00016337190673426118
fs.RO.feed_side.properties_in[0.0].conc_mass_phase_comp[Liq,H2O]: 985.7089
fs.RO.feed_side.properties_in[0.0].conc_mass_phase_comp[Liq,NaCl]: 35.75110000000001
fs.RO.feed_side.properties_in[0.0].dens_mass_phase[Liq]: 1021.46
fs.RO.feed_side.properties_in[0.0].diffus_phase_comp[Liq,NaCl]: 1.4718713456250002e-09
fs.RO.feed_side.properties_in[0.0].enth_mass_phase[Liq]: 99740.72571999993
fs.RO.feed_side.properties_in[0.0].flow_mass_phase_comp[Liq,H2O]: 0.9857088999999999
fs.RO.feed_side.properties_in[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035751099999999994
fs.RO.feed_side.properties_in[0.0].flow_vol_phase[Liq]: 0.0009999999999999998
fs.RO.feed_side.properties_in[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.RO.feed_side.properties_in[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.RO.feed_side.properties_in[0.0].pressure: 7492887.151347015
fs.RO.feed_side.properties_in[0.0].temperature: 298.15
fs.RO.feed_side.properties_in[0.0].visc_d_phase[Liq]: 0.00105525
fs.RO.feed_side.properties_interface[0.0,0.0].conc_mass_phase_comp[Liq,H2O]: 982.3943007903467
fs.RO.feed_side.properties_interface[0.0,0.0].conc_mass_phase_comp[Liq,NaCl]: 47.411106122365666
fs.RO.feed_side.properties_interface[0.0,0.0].dens_mass_phase[Liq]: 1029.8054069127124
fs.RO.feed_side.properties_interface[0.0,0.0].flow_mass_phase_comp[Liq,H2O]: 0.9823943007903467
fs.RO.feed_side.properties_interface[0.0,0.0].flow_mass_phase_comp[Liq,NaCl]: 0.04741110612236568
fs.RO.feed_side.properties_interface[0.0,0.0].flow_vol_phase[Liq]: 0.001
fs.RO.feed_side.properties_interface[0.0,0.0].mass_frac_phase_comp[Liq,H2O]: 0.9539611019673115
fs.RO.feed_side.properties_interface[0.0,0.0].mass_frac_phase_comp[Liq,NaCl]: 0.04603889803268852
fs.RO.feed_side.properties_interface[0.0,0.0].molality_phase_comp[Liq,NaCl]: 0.8258174321622521
fs.RO.feed_side.properties_interface[0.0,0.0].osm_coeff: 0.9325211922848624
fs.RO.feed_side.properties_interface[0.0,0.0].pressure: 7492887.151347015
fs.RO.feed_side.properties_interface[0.0,0.0].pressure_osm_phase[Liq]: 3818051.2250656686
fs.RO.feed_side.properties_interface[0.0,0.0].temperature: 298.15
fs.RO.feed_side.properties_interface[0.0,1.0].conc_mass_phase_comp[Liq,H2O]: 973.3500702906201
fs.RO.feed_side.properties_interface[0.0,1.0].conc_mass_phase_comp[Liq,NaCl]: 77.21448026228654
fs.RO.feed_side.properties_interface[0.0,1.0].dens_mass_phase[Liq]: 1050.5645505529067
fs.RO.feed_side.properties_interface[0.0,1.0].flow_mass_phase_comp[Liq,H2O]: 0.49178035623654887
fs.RO.feed_side.properties_interface[0.0,1.0].flow_mass_phase_comp[Liq,NaCl]: 0.03901223801080068
fs.RO.feed_side.properties_interface[0.0,1.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.RO.feed_side.properties_interface[0.0,1.0].mass_frac_phase_comp[Liq,H2O]: 0.9265019172580599
fs.RO.feed_side.properties_interface[0.0,1.0].mass_frac_phase_comp[Liq,NaCl]: 0.07349808274193999
fs.RO.feed_side.properties_interface[0.0,1.0].molality_phase_comp[Liq,NaCl]: 1.357436368583309
fs.RO.feed_side.properties_interface[0.0,1.0].osm_coeff: 0.9511116629361246
fs.RO.feed_side.properties_interface[0.0,1.0].pressure: 7348667.029398319
fs.RO.feed_side.properties_interface[0.0,1.0].pressure_osm_phase[Liq]: 6401031.9196097
fs.RO.feed_side.properties_interface[0.0,1.0].temperature: 298.1500072638073
fs.RO.feed_side.properties_out[0.0].conc_mass_phase_comp[Liq,H2O]: 975.4759568310151
fs.RO.feed_side.properties_out[0.0].conc_mass_phase_comp[Liq,NaCl]: 70.43656218021442
fs.RO.feed_side.properties_out[0.0].dens_mass_phase[Liq]: 1045.9125190112295
fs.RO.feed_side.properties_out[0.0].diffus_phase_comp[Liq,NaCl]: 1.4777080552946597e-09
fs.RO.feed_side.properties_out[0.0].enth_mass_phase[Liq]: 94955.13833890572
fs.RO.feed_side.properties_out[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.RO.feed_side.properties_out[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035587728093265734
fs.RO.feed_side.properties_out[0.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.RO.feed_side.properties_out[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9326553981332943
fs.RO.feed_side.properties_out[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.06734460186670564
fs.RO.feed_side.properties_out[0.0].molality_phase_comp[Liq,NaCl]: 1.2355814350006222
fs.RO.feed_side.properties_out[0.0].osm_coeff: 0.9463005884768287
fs.RO.feed_side.properties_out[0.0].pressure: 7348667.029398319
fs.RO.feed_side.properties_out[0.0].pressure_osm_phase[Liq]: 5796949.131264621
fs.RO.feed_side.properties_out[0.0].temperature: 298.1500072638073
fs.RO.feed_side.properties_out[0.0].visc_d_phase[Liq]: 0.001124790894013417
fs.RO.flux_mass_phase_comp[0.0,0.0,Liq,H2O]: 0.009780145390605626
fs.RO.flux_mass_phase_comp[0.0,0.0,Liq,NaCl]: 1.5603828130075665e-06
fs.RO.flux_mass_phase_comp[0.0,1.0,Liq,H2O]: 0.0025203426959829727
fs.RO.flux_mass_phase_comp[0.0,1.0,Liq,NaCl]: 2.516995797387531e-06
fs.RO.feed_side.friction_factor_darcy[0.0,0.0]: 0.9776020559136095
fs.RO.feed_side.friction_factor_darcy[0.0,1.0]: 1.568853595733793
fs.RO.length: 16.027151005084633
fs.RO.mass_transfer_phase_comp[0.0,Liq,H2O]: 0.49285444999999994
fs.RO.mass_transfer_phase_comp[0.0,Liq,NaCl]: 0.00016337190673426118
fs.RO.over_pressure_ratio[0.0]: 1.2849198769297012
fs.RO.permeate_side[0.0,0.0].conc_mass_phase_comp[Liq,H2O]: 994.961855357415
fs.RO.permeate_side[0.0,0.0].conc_mass_phase_comp[Liq,NaCl]: 0.15874215737008507
fs.RO.permeate_side[0.0,0.0].dens_mass_phase[Liq]: 995.1205975147851
fs.RO.permeate_side[0.0,0.0].flow_mass_phase_comp[Liq,H2O]: 0.492874827607592
fs.RO.permeate_side[0.0,0.0].flow_mass_phase_comp[Liq,NaCl]: 7.863619396718698e-05
fs.RO.permeate_side[0.0,0.0].flow_vol_phase[Liq]: 0.0004953705762222806
fs.RO.permeate_side[0.0,0.0].mass_frac_phase_comp[Liq,H2O]: 0.9998404794777974
fs.RO.permeate_side[0.0,0.0].mass_frac_phase_comp[Liq,NaCl]: 0.00015952052220256303
fs.RO.permeate_side[0.0,0.0].molality_phase_comp[Liq,NaCl]: 0.002730081674529446
fs.RO.permeate_side[0.0,0.0].osm_coeff: 0.918014306572665
fs.RO.permeate_side[0.0,0.0].pressure: 101325.0
fs.RO.permeate_side[0.0,0.0].pressure_osm_phase[Liq]: 12425.792420200445
fs.RO.permeate_side[0.0,0.0].temperature: 298.1500072638073
fs.RO.mixed_permeate[0.0].conc_mass_phase_comp[Liq,H2O]: 994.9207192694635
fs.RO.mixed_permeate[0.0].conc_mass_phase_comp[Liq,NaCl]: 0.32979735692043527
fs.RO.mixed_permeate[0.0].dens_mass_phase[Liq]: 995.2505166263837
fs.RO.mixed_permeate[0.0].enth_mass_phase[Liq]: 104870.16751044188
fs.RO.mixed_permeate[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.RO.mixed_permeate[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.00016337190673426118
fs.RO.mixed_permeate[0.0].flow_vol_phase[Liq]: 0.0004953705762222806
fs.RO.mixed_permeate[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9996686288010798
fs.RO.mixed_permeate[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.0003313711989202021
fs.RO.mixed_permeate[0.0].temperature: 298.1500072638073
fs.RO.permeate_side[0.0,1.0].conc_mass_phase_comp[Liq,H2O]: 994.7608030190643
fs.RO.permeate_side[0.0,1.0].conc_mass_phase_comp[Liq,NaCl]: 0.9934398066562586
fs.RO.permeate_side[0.0,1.0].dens_mass_phase[Liq]: 995.7542428257206
fs.RO.permeate_side[0.0,1.0].flow_mass_phase_comp[Liq,H2O]: 0.4927752321948925
fs.RO.permeate_side[0.0,1.0].flow_mass_phase_comp[Liq,NaCl]: 0.0004921208494654619
fs.RO.permeate_side[0.0,1.0].flow_vol_phase[Liq]: 0.0004953705762222807
fs.RO.permeate_side[0.0,1.0].mass_frac_phase_comp[Liq,H2O]: 0.9990023243046023
fs.RO.permeate_side[0.0,1.0].mass_frac_phase_comp[Liq,NaCl]: 0.0009976756953975975
fs.RO.permeate_side[0.0,1.0].molality_phase_comp[Liq,NaCl]: 0.017088844049038147
fs.RO.permeate_side[0.0,1.0].osm_coeff: 0.9180935905247434
fs.RO.permeate_side[0.0,1.0].pressure: 101325.0
fs.RO.permeate_side[0.0,1.0].pressure_osm_phase[Liq]: 77785.49986539404
fs.RO.permeate_side[0.0,1.0].temperature: 298.1500072638073
fs.RO.recovery_mass_phase_comp[0.0,Liq,NaCl]: 0.00456970293877003
fs.RO.recovery_vol_phase[0.0,Liq]: 0.49537057622228065
fs.RO.rejection_phase_comp[0.0,Liq,NaCl]: 0.9907751829476453
fs.RO.feed_side.velocity[0.0,0.0]: 0.2072813645716875
fs.RO.feed_side.velocity[0.0,1.0]: 0.10472789433284409
fs.S1.P1_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.48768430557756287
fs.S1.P1_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.017688031808512642
fs.S1.P1_state[0.0].pressure: 101325.0
fs.S1.P1_state[0.0].temperature: 298.15
fs.S1.PXR_state[0.0].dens_mass_phase[Liq]: 1021.46
fs.S1.PXR_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.498024594422437
fs.S1.PXR_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.018063068191487355
fs.S1.PXR_state[0.0].flow_vol_phase[Liq]: 0.0005052451027097726
fs.S1.PXR_state[0.0].mass_frac_phase_comp[Liq,H2O]: 0.965
fs.S1.PXR_state[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.S1.PXR_state[0.0].pressure: 101325.0
fs.S1.PXR_state[0.0].temperature: 298.15
fs.S1.mixed_state[0.0].flow_mass_phase_comp[Liq,H2O]: 0.9857088999999999
fs.S1.mixed_state[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.0357511
fs.S1.mixed_state[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9650000000000001
fs.S1.mixed_state[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.03500000000000001
fs.S1.mixed_state[0.0].pressure: 101325.0
fs.S1.mixed_state[0.0].temperature: 298.15
fs.S1.split_fraction[0.0,P1]: 0.49475489729022726
fs.S1.split_fraction[0.0,PXR]: 0.5052451027097727
fs.costing.LCOW: 0.46090440122852394
fs.costing.aggregate_capital_cost: 12709.589772436626
fs.costing.total_capital_cost: 25419.179544873252
fs.costing.maintenance_labor_chemical_operating_cost: 762.5753863461975
fs.costing.total_operating_cost: 3942.7469500005436
fs.disposal.properties[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.disposal.properties[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.035587728093265734
fs.disposal.properties[0.0].pressure: 101325.0
fs.disposal.properties[0.0].temperature: 298.1500072638073
fs.feed.properties[0.0].dens_mass_phase[Liq]: 1021.46
fs.feed.properties[0.0].flow_vol_phase[Liq]: 0.0009999999999999998
fs.feed.properties[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9650000000000001
fs.feed.properties[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.035
fs.product.properties[0.0].dens_mass_phase[Liq]: 995.2505166263836
fs.product.properties[0.0].flow_mass_phase_comp[Liq,H2O]: 0.49285444999999994
fs.product.properties[0.0].flow_mass_phase_comp[Liq,NaCl]: 0.0001633719067342612
fs.product.properties[0.0].flow_vol_phase[Liq]: 0.0004953705762222808
fs.product.properties[0.0].mass_frac_phase_comp[Liq,H2O]: 0.9996686288010798
fs.product.properties[0.0].mass_frac_phase_comp[Liq,NaCl]: 0.00033137119892020215
fs.product.properties[0.0].pressure: 101325.0
fs.product.properties[0.0].temperature: 298.1500072638073
